name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run linters on example
    runs-on: ubuntu-latest
    steps:
      - name: Clone sources
        uses: actions/checkout@v3
      - name: Run linters
        run: |
          python -m pip install pip -U
          python -m pip install -r requirements.txt
          python -m qualamity example -I example/include -f github
